### ISSUE TITLE
404 error when downloading 1.3.0 update

### ISSUE THREAD

**Issue by ghost** [dracula/atom#1]
The latest update still appears to use the old GitHub repository, not the new one, and a 404 error is received. I got a more ambiguous error when installing it using the program itself.

``` bash
$ apm update
Package Updates Available (1)
└── dracula-theme 1.2.5 -> 1.3.0

Would you like to install these updates? (yes) y

Installing dracula-theme@1.3.0 to /home/patrick/.atom/packages ✗
Unable to download https://www.atom.io/api/packages/dracula-theme/versions/1.3.0/tarball: 404
```

**Comment by nesl247** [comment]
We're currently working on updating APM to use the new repository.

**Comment by ghost** [comment]
Thanks. :smiley_cat:

**Comment by zenorocha** [comment]
I just unpublished that ghost version. Sorry about that
