### ISSUE TITLE
Bracket matching is not highlighted properly 

### ISSUE THREAD

**Issue by dcrystalj** [dracula/atom#2]
Bracket matching is not highlighted properly with atom 18 +,  python3 and dracula theme
![Image of dracula](http://storage6.static.itmages.com/i/16/0606/h_1465254383_2920467_d20a07b715.jpeg)

But it is highlighted properly with atom dark fore example:
![Image of atom dark](http://storage8.static.itmages.com/i/16/0606/h_1465254442_5202231_e6e04a4e4b.jpeg)

**Comment by qolop** [comment]
Whatever is causing this, I don't see how it could be the fault of the Dracula theme. I'd suggest making sure your editor is updated. I'm using the latest release of Atom (1.8.0 at the time of writing), and there are green dots under opening and closing brackets in every language, including Python 3, which are bright and easy for me to see.

![The green dots under the brackets.](https://i.imgur.com/dmS3ghf.png)

**Comment by ghost** [comment]
Not sure what causes this at the moment, but I found that Dracula only adds the highlighting under brackets if the brackets are on a different line.

![](https://i.imgur.com/mUxqaOh.png)
vs
![](https://i.imgur.com/4yptrjt.png)

**Comment by dcrystalj** [comment]
@qolop interesting thing is that only second bracket gets highlighted, if you have cursor on first bracket and second one is in different line.

**Comment by JimmyMultani** [comment]
I will look into this later tonight. Thanks!

**Comment by ghost** [comment]
Just issued a pull request for it that fixes the issue.
