### ISSUE TITLE
Take new screenshot

### ISSUE THREAD

**Issue by zenorocha** [dracula/atom#21]
Hey @JimmyMultani!

Can you update the screenshot to use the new code snippet?

## New Snippet

```js
/*
 * Once upon a time...
 */

class Vampire {
  constructor(props) {
    this.location = props.location;
    this.birthDate = props.birthDate;
    this.deathDate = props.deathDate;
    this.weaknesses = props.weaknesses;
  }

  get age() {
    return this.calcAge();
  }

  calcAge() {
    return this.deathDate - this.birthDate;
  }
}

// ...there was a guy named Vlad

const Dracula = new Vampire({
  location: 'Transylvania',
  birthDate: 1428,
  deathDate: 1476,
  weaknesses: ['Sunlight', 'Garlic']
}); 
```

## Why use this?

* It contains examples of string, number, and array
* It contains examples of single line and multi-line comments
* It contains examples of inheritance and functions
* It's simple, funny, and silly

## Want to use another language?

Feel free to send a pull request to the [template repo](https://github.com/dracula/template) under the `sample` folder.

**Comment by JimmyMultani** [comment]
Hey @zenorocha, I'll work on it tonight or tomorrow. Thanks!

**Comment by JimmyMultani** [comment]
Seems like this syntax theme needs to follow the new Dracula Specification still, so I've decided to work on that before I update the screenshot, as I'd have to do it again after it follows the spec.

It can be found here: #22 

Thanks!

**Comment by zenorocha** [comment]
Got it, thanks @JimmyMultani!

**Comment by zenorocha** [comment]
Friendly ping ;)

**Comment by JimmyMultani** [comment]
Sorry about that, works been getting pretty busy. I'll space out some time to work on it tomorrow.

**Comment by zenorocha** [comment]
Totally understand @JimmyMultani, I'm just making sure we don't forget about it :)

**Comment by JimmyMultani** [comment]
Done. Thanks for waiting!
