### ISSUE TITLE
Dracula-syntax 3.0.0 doesn't seem right

### ISSUE THREAD

**Issue by WaKeMaTTa** [dracula/atom#23]
I just updated from `dracula-syntax 2.0.7` to `dracula-syntax 3.0.0`.

And in this release you mess up the whole syntax. :sob: 

![Screenshot from 2020-05-14 13-50-17](https://user-images.githubusercontent.com/3450257/81931128-e6c7e500-95e9-11ea-9ceb-7f87b88b8867.png)

**Comment by JimmyMultani** [comment]
Hey @WaKeMaTTa, sorry for the breakage. I'll look into it. If you have some sample code I could use to help debug, that would be super useful. Thanks!

**Comment by WaKeMaTTa** [comment]
@JimmyMultani thank you for the effort.

You can use any `.rb` file from the repo [`rails`](https://github.com/rails/rails)

I can suggest you this file: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/validations.rb

I'm using `ruby on rails` language:

![Screenshot from 2020-05-14 17-04-03](https://user-images.githubusercontent.com/3450257/81951015-f143a800-9604-11ea-8f4a-f726965abba6.png)


---

PS: if is too complicated to fix, don't bother. I can always use another atom syntax package.

**Comment by being-frank** [comment]
Hi @JimmyMultani 

I am also experiencing the same problems. Here are two Ruby and JS comparisons

v3.0.0
![healthforce 2020-05-14 22-46-04](https://user-images.githubusercontent.com/655991/81984224-c8d3a200-9634-11ea-9f26-43df0ab87fe7.png)

v.2.0.7
![healthforce 2020-05-14 22-49-20](https://user-images.githubusercontent.com/655991/81984509-2bc53900-9635-11ea-86ea-a110ebf04d4a.png)

**Comment by JimmyMultani** [comment]
@franks921 Yeah, v3 is following the new spec which can be found here: https://spec.draculatheme.com/

There may be some issues with it still, and I'll do what I can to fix them. 

PRs are also welcome! 😄

**Comment by JimmyMultani** [comment]
@WaKeMaTTa @franks921 I just pushed out a patch fix. Can you let me know if there are any other discrepancies? Thank you again for bringing this to my attention.

**Comment by being-frank** [comment]
Hi @JimmyMultani, apologies for the late response. I just had a look and it still is wrong compared to 2.0.7 not just for Ruby, but Javascript also.

v.2.0.7
![healthforce 2020-05-17 17-58-22](https://user-images.githubusercontent.com/655991/82153574-87c3d380-9868-11ea-8467-362d91d8ae2d.png)

v.3.0.1
![healthforce 2020-05-17 18-02-40](https://user-images.githubusercontent.com/655991/82153590-9dd19400-9868-11ea-9e60-5fc71aa649ba.png)

**Comment by being-frank** [comment]
Sorry, one more thing... Here is a screenshot of VSCode which almost 100% matches v.2.0.7

![hcp_lobby_controller rb — healthforce 2020-05-17 18-10-29](https://user-images.githubusercontent.com/655991/82153745-b42c1f80-9869-11ea-844d-959fca06d489.png)

**Comment by JimmyMultani** [comment]
Made another push with hopefully more fixes in tow. I feel I should re-emphasize that v3 is following the new spec which can be found here: https://spec.draculatheme.com/

What that means is that it won't look identically to what v2 looked like, since the Dracula Org is trying to create some consistency among its themes.

**Comment by WaKeMaTTa** [comment]
I updated to 3.0.1 and now is much better. Thank you @JimmyMultani

**Comment by being-frank** [comment]
Thanks for the effort @JimmyMultani. I've been looking at the new spec and unfortunately my eyes can't get used to the new version (I tried 3.0.2) :( 

Sorry for letting you run around in circles. Feel free to close the issue if @WaKeMaTTa is happy 👍
