### ISSUE TITLE
the first guide line is not showing with the default atom themes ui

### ISSUE THREAD

**Issue by tinchoz49** [dracula/atom#4]
Hi, i noticed that using `Atom Dark/Light UI` and `Atom One Dark/Light UI` with the dracula syntax the first guide line is not showing.

I'm using Atom 1.9-beta.

![screenshot_2016-06-16_17-53-25](https://cloud.githubusercontent.com/assets/819446/16132846/54b10f2a-33eb-11e6-9cc4-6620ae9e6b3c.png)

Beautiful syntax by the way! :+1:

**Comment by JimmyMultani** [comment]
Thanks @tinchoz49, I'll check this out later tonight.

**Comment by JimmyMultani** [comment]
Thanks for reporting this, @tinchoz49! It'll be in the next update. :)
