### ISSUE TITLE
Code Block have different background color

### ISSUE THREAD

**Issue by nerdpad** [dracula/atom#6]
The background color of code while using Dracula theme is not correct (It used to be before the update).

It works fine with One Dark UI theme, but has problem with others. I tried Seti UI, Dracula UI. 

Atom Version: 1.10.2
UI Theme: https://github.com/vermotr/seti-classic

<img width="452" alt="screen shot 2016-10-04 at 11 21 41 am" src="https://cloud.githubusercontent.com/assets/87896/19080534/5ff5070c-8a25-11e6-87aa-a3711613cdc1.png">

**Comment by JimmyMultani** [comment]
Hey @NerdPad,

I'm having a little trouble reproducing this, can you provide me with a bit more info?

Which language set is this occurring in? Can you provide us with a larger image so we can see where exactly this is happening?

Thanks!

**Comment by nerdpad** [comment]
Earlier I tried with Ruby & JavaScript, restarted Atom multiple times but it didn't work.

But I installed another theme, changed to that, and then reverted back to the UI theme I was using and it's working properly.

I can't recreate it anymore. Will reopen if I find the reason.

**Comment by nerdpad** [comment]
<img width="757" alt="screen shot 2016-10-13 at 11 18 16 am" src="https://cloud.githubusercontent.com/assets/87896/19355148/4e78e368-9137-11e6-874f-3767cffad7d2.png">

I am not sure why this is happening. Any pointers?

**Comment by JimmyMultani** [comment]
Hey @NerdPad, is this still happening when you restart Atom? Does this happen after you've used Atom for some time? Thanks.

**Comment by nerdpad** [comment]
It happens once I have used it for sometime, and then doesn't go away after restarting Atom. If I change the theme back to something else, restart, and then use Dracula, then it works fine for sometime.

**Comment by nerdpad** [comment]
I think this might be an issue with the seti-classic theme that I am using.
