### ISSUE TITLE
Update stylesheet for removal of shadow DOM in Atom 1.13

### ISSUE THREAD

**Issue by alexrussell** [dracula/atom#8]
In Atom 1.13 Beta (and eventually in stable) the shadow DOM 'experiment' has been removed for the `atom-text-editor` element. Now, you simply prepend all grammar scope names with `syntax--` in order to target them.

Relevant information:

- [Blog post](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html)
- [Guid to upgrade](http://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles/)
- [Example upgrade on Atom dark syntax theme](https://github.com/atom/atom-dark-syntax/pull/31/files)
- [Pull request for actual removal (has some possibly useful information)](https://github.com/atom/atom/pull/12903)

**Comment by JimmyMultani** [comment]
Hey @alexrussell,

Thanks for reporting this issue. If you're willing, you can request a PR and I can merge it in. Otherwise, I'll get around to it this weekend.

Thanks!

**Comment by alexrussell** [comment]
Done, hopefully correctly. See #9.
